// Shared demo seed data for KisanMitra.
//
// Single source of truth for the demo marketplace catalog: products, offers and
// MSAMB reference market prices. The Prisma seed script (backend/prisma/seed.js),
// the in-memory fallback controllers (products/offers/market-prices) and the demo
// data-integrity tests all read from this module so database mode and in-memory
// mode always expose the SAME demo records.
//
// The records are clearly demo data: market prices use source 'MSAMB' and are
// reference values, never live quotes (the app renders a "not live" notice).
// Products/offers use fixed demo ids (p1..p6, o1..o15) and demo seller names so
// re-seeding can never create duplicates (the seed wipes only the demo tables:
// product/requirement/offer/order/marketPrice — user accounts are NOT touched).
//
// Consumers:
//   - backend/prisma/seed.js        -> writes these rows to MySQL (see seed:demo)
//   - controllers/productsController -> in-memory GET /api/products fallback
//   - controllers/offersController   -> in-memory product-offer fallback
//   - services/marketPriceService    -> in-memory GET /api/market-prices fallback
//   - test/demoSeedIntegrity.test.js -> integrity + DB/in-memory parity checks

// Reserved demo requirement ids used by the linked offers (seeded with the
// requirements in seed.js). Kept here so integrity tests can validate refs.
const DEMO_REQUIREMENT_IDS = ['r1', 'r2'];

const products = [
  {
    id: 'p1',
    name: 'Basmati Rice',
    category: 'Grains',
    grade: 'A',
    quantity: 120,
    unit: 'Quintal',
    pricePerQuintal: 4200,
    seller: 'AgroMart Traders',
    sellerUserId: null,
    sellerRating: 4.6,
    verified: true,
    location: 'Nashik, MH',
    distanceKm: 12,
    transportCost: 600,
    otherCosts: 250,
    dealScore: 92,
    imageFile: 'basmati-rice.png',
    description:
      'Premium long-grain Basmati rice, freshly harvested and cleaned. Ideal for bulk buyers and retailers.',
  },
  {
    id: 'p2',
    name: 'Soybean',
    category: 'Oilseeds',
    grade: 'A+',
    quantity: 300,
    unit: 'Quintal',
    pricePerQuintal: 5600,
    seller: 'GreenFields Co-op',
    sellerUserId: null,
    sellerRating: 4.8,
    verified: true,
    location: 'Latur, MH',
    distanceKm: 45,
    transportCost: 1400,
    otherCosts: 400,
    dealScore: 88,
    imageFile: 'soybean.png',
    description:
      'High-protein soybean with excellent oil yield. Suitable for crushers and processors.',
  },
  {
    id: 'p3',
    name: 'Red Onion',
    category: 'Vegetables',
    grade: 'A',
    quantity: 80,
    unit: 'Quintal',
    pricePerQuintal: 1800,
    seller: 'Lasalgaon APMC',
    sellerUserId: null,
    sellerRating: 4.3,
    verified: false,
    location: 'Lasalgaon, MH',
    distanceKm: 8,
    transportCost: 250,
    otherCosts: 120,
    dealScore: 90,
    imageFile: 'red-onion.png',
    description:
      'Fresh red onions from Lasalgaon market, graded and sorted. Good storage shelf life.',
  },
  {
    id: 'p4',
    name: 'Wheat (Sharbati)',
    category: 'Grains',
    grade: 'A',
    quantity: 200,
    unit: 'Quintal',
    pricePerQuintal: 2400,
    seller: 'MP Grain Exports',
    sellerUserId: null,
    sellerRating: 4.5,
    verified: true,
    location: 'Indore, MP',
    distanceKm: 380,
    transportCost: 5200,
    otherCosts: 800,
    dealScore: 61,
    imageFile: 'wheat.png',
    description:
      'Sharbati variety wheat known for premium quality. Best suited for flour milling.',
  },
  {
    id: 'p5',
    name: 'Tur Dal',
    category: 'Pulses',
    grade: 'A',
    quantity: 90,
    unit: 'Quintal',
    pricePerQuintal: 8200,
    seller: 'PulseHub Distributors',
    sellerUserId: null,
    sellerRating: 4.7,
    verified: true,
    location: 'Akola, MH',
    distanceKm: 60,
    transportCost: 1800,
    otherCosts: 350,
    dealScore: 85,
    imageFile: 'tur-dal.png',
    description:
      'Clean, sorted Tur (Arhar) dal with high protein content. Good for wholesale buyers.',
  },
  {
    id: 'p6',
    name: 'Fresh Mango (Kesar)',
    category: 'Fruits',
    grade: 'A+',
    quantity: 40,
    unit: 'Tonne',
    pricePerQuintal: 7800,
    seller: 'Sindhudurg Farms',
    sellerUserId: null,
    sellerRating: 4.9,
    verified: true,
    location: 'Ratnagiri, MH',
    distanceKm: 150,
    transportCost: 3200,
    otherCosts: 900,
    dealScore: 78,
    imageFile: 'kesar-mango.png',
    description:
      'Premium Kesar mangoes, handpicked and graded. Export quality, promptly dispatched.',
  },
];

// o1..o6 are requirement-linked offers (Basmati Rice, Red Onion). o7..o15 are
// product-linked offers (Soybean, Wheat, Tur Dal, Kesar Mango) added so the
// "Compare Deals" screen has at least two sellers to compare for every product.
const offers = [
  {
    id: 'o1',
    requirementId: 'r1',
    productId: 'p1',
    sellerName: 'AgroMart Traders',
    sellerRating: 4.6,
    verified: true,
    quantity: 120,
    unit: 'Quintal',
    offeredPricePerQuintal: 4400,
    distanceKm: 12,
    transportCostPerQuintal: 50,
    otherCostsPerQuintal: 20,
    dealScore: 91,
    shortlisted: true,
  },
  {
    id: 'o2',
    requirementId: 'r1',
    productId: 'p1',
    sellerName: 'GreenFields Co-op',
    sellerRating: 4.8,
    verified: true,
    quantity: 120,
    unit: 'Quintal',
    offeredPricePerQuintal: 4500,
    distanceKm: 45,
    transportCostPerQuintal: 120,
    otherCostsPerQuintal: 35,
    dealScore: 84,
    shortlisted: false,
  },
  {
    id: 'o3',
    requirementId: 'r1',
    productId: 'p1',
    sellerName: 'MP Grain Exports',
    sellerRating: 4.5,
    verified: true,
    quantity: 120,
    unit: 'Quintal',
    offeredPricePerQuintal: 4650,
    distanceKm: 380,
    transportCostPerQuintal: 430,
    otherCostsPerQuintal: 70,
    dealScore: 62,
    shortlisted: false,
  },
  {
    id: 'o4',
    requirementId: 'r2',
    productId: 'p3',
    sellerName: 'Lasalgaon APMC',
    sellerRating: 4.3,
    verified: false,
    quantity: 80,
    unit: 'Quintal',
    offeredPricePerQuintal: 1750,
    distanceKm: 8,
    transportCostPerQuintal: 25,
    otherCostsPerQuintal: 15,
    dealScore: 92,
    shortlisted: false,
  },
  {
    id: 'o5',
    requirementId: 'r2',
    productId: 'p3',
    sellerName: 'AgroMart Traders',
    sellerRating: 4.6,
    verified: true,
    quantity: 80,
    unit: 'Quintal',
    offeredPricePerQuintal: 1820,
    distanceKm: 15,
    transportCostPerQuintal: 30,
    otherCostsPerQuintal: 10,
    dealScore: 86,
    shortlisted: false,
  },
  {
    id: 'o6',
    requirementId: 'r2',
    productId: 'p3',
    sellerName: 'GreenFields Co-op',
    sellerRating: 4.8,
    verified: true,
    quantity: 80,
    unit: 'Quintal',
    offeredPricePerQuintal: 1800,
    distanceKm: 45,
    transportCostPerQuintal: 90,
    otherCostsPerQuintal: 25,
    dealScore: 79,
    shortlisted: false,
  },
  {
    id: 'o7',
    requirementId: null,
    productId: 'p2',
    sellerName: 'AgroMart Traders',
    sellerRating: 4.6,
    verified: true,
    quantity: 300,
    unit: 'Quintal',
    offeredPricePerQuintal: 5480,
    distanceKm: 12,
    transportCostPerQuintal: 45,
    otherCostsPerQuintal: 15,
    dealScore: 89,
    shortlisted: true,
  },
  {
    id: 'o8',
    requirementId: null,
    productId: 'p2',
    sellerName: 'MP Grain Exports',
    sellerRating: 4.5,
    verified: true,
    quantity: 300,
    unit: 'Quintal',
    offeredPricePerQuintal: 5550,
    distanceKm: 380,
    transportCostPerQuintal: 320,
    otherCostsPerQuintal: 30,
    dealScore: 55,
    shortlisted: false,
  },
  {
    id: 'o9',
    requirementId: null,
    productId: 'p2',
    sellerName: 'PulseHub Distributors',
    sellerRating: 4.7,
    verified: true,
    quantity: 300,
    unit: 'Quintal',
    offeredPricePerQuintal: 5420,
    distanceKm: 60,
    transportCostPerQuintal: 55,
    otherCostsPerQuintal: 18,
    dealScore: 82,
    shortlisted: false,
  },
  {
    id: 'o10',
    requirementId: null,
    productId: 'p4',
    sellerName: 'MP Grain Exports',
    sellerRating: 4.5,
    verified: true,
    quantity: 200,
    unit: 'Quintal',
    offeredPricePerQuintal: 2320,
    distanceKm: 380,
    transportCostPerQuintal: 280,
    otherCostsPerQuintal: 35,
    dealScore: 58,
    shortlisted: false,
  },
  {
    id: 'o11',
    requirementId: null,
    productId: 'p4',
    sellerName: 'AgroMart Traders',
    sellerRating: 4.6,
    verified: true,
    quantity: 200,
    unit: 'Quintal',
    offeredPricePerQuintal: 2380,
    distanceKm: 120,
    transportCostPerQuintal: 90,
    otherCostsPerQuintal: 20,
    dealScore: 78,
    shortlisted: true,
  },
  {
    id: 'o12',
    requirementId: null,
    productId: 'p5',
    sellerName: 'PulseHub Distributors',
    sellerRating: 4.7,
    verified: true,
    quantity: 90,
    unit: 'Quintal',
    offeredPricePerQuintal: 8000,
    distanceKm: 60,
    transportCostPerQuintal: 210,
    otherCostsPerQuintal: 40,
    dealScore: 80,
    shortlisted: true,
  },
  {
    id: 'o13',
    requirementId: null,
    productId: 'p5',
    sellerName: 'AgroMart Traders',
    sellerRating: 4.6,
    verified: true,
    quantity: 90,
    unit: 'Quintal',
    offeredPricePerQuintal: 8120,
    distanceKm: 120,
    transportCostPerQuintal: 310,
    otherCostsPerQuintal: 50,
    dealScore: 73,
    shortlisted: false,
  },
  {
    id: 'o14',
    requirementId: null,
    productId: 'p6',
    sellerName: 'Sindhudurg Farms',
    sellerRating: 4.9,
    verified: true,
    quantity: 40,
    unit: 'Tonne',
    offeredPricePerQuintal: 7600,
    distanceKm: 150,
    transportCostPerQuintal: 800,
    otherCostsPerQuintal: 200,
    dealScore: 72,
    shortlisted: false,
  },
  {
    id: 'o15',
    requirementId: null,
    productId: 'p6',
    sellerName: 'GreenFields Co-op',
    sellerRating: 4.8,
    verified: true,
    quantity: 40,
    unit: 'Tonne',
    offeredPricePerQuintal: 7850,
    distanceKm: 45,
    transportCostPerQuintal: 230,
    otherCostsPerQuintal: 90,
    dealScore: 84,
    shortlisted: true,
  },
];

// Primary MSAMB reference date. Rows may carry an explicit earlier `referenceDate`
// so the seed contains multiple dated batches (5 records on 2026-09-02) that the
// comparison screens can show without ever creating duplicate crop+market cards.
const MSAMB_DATE = '2026-09-03';

const marketPrices = [
  // Onion — main Maharashtra markets plus Delhi (Azadpur) and UP (Varanasi).
  { cropName: 'Onion', marketName: 'Ahmednagar', pricePerQtl: 3100 },
  { cropName: 'Onion', marketName: 'Solapur', pricePerQtl: 3400 },
  { cropName: 'Onion', marketName: 'Lasalgaon', pricePerQtl: 4525 },
  { cropName: 'Onion', marketName: 'Pune', pricePerQtl: 3500 },
  { cropName: 'Onion', marketName: 'Nashik', pricePerQtl: 3600 },
  { cropName: 'Onion', marketName: 'Azadpur', pricePerQtl: 4200 },
  { cropName: 'Onion', marketName: 'Varanasi', pricePerQtl: 3800 },
  { cropName: 'Onion', marketName: 'Sangli', pricePerQtl: 3100, referenceDate: '2026-09-02' },
  // Soybean
  { cropName: 'Soybean', marketName: 'Akola', pricePerQtl: 6080 },
  { cropName: 'Soybean', marketName: 'Amravati', pricePerQtl: 5900 },
  { cropName: 'Soybean', marketName: 'Sangli', pricePerQtl: 6850 },
  // Tur
  { cropName: 'Tur', marketName: 'Akola', pricePerQtl: 8255 },
  { cropName: 'Tur', marketName: 'Amravati', pricePerQtl: 8325 },
  // Wheat
  { cropName: 'Wheat', marketName: 'Solapur', pricePerQtl: 3665 },
  { cropName: 'Wheat', marketName: 'Pune', pricePerQtl: 2400 },
  { cropName: 'Wheat', marketName: 'Nashik', pricePerQtl: 2450 },
  { cropName: 'Wheat', marketName: 'Varanasi', pricePerQtl: 2550 },
  { cropName: 'Wheat', marketName: 'Azadpur', pricePerQtl: 2350 },
  { cropName: 'Wheat', marketName: 'Aligarh', pricePerQtl: 2250, referenceDate: '2026-09-02' },
  // Maize
  { cropName: 'Maize', marketName: 'Lasalgaon', pricePerQtl: 2551 },
  // Tomato
  { cropName: 'Tomato', marketName: 'Lasalgaon', pricePerQtl: 2400 },
  { cropName: 'Tomato', marketName: 'Nashik', pricePerQtl: 2300 },
  { cropName: 'Tomato', marketName: 'Pune', pricePerQtl: 2200 },
  { cropName: 'Tomato', marketName: 'Azadpur', pricePerQtl: 2100 },
  { cropName: 'Tomato', marketName: 'Varanasi', pricePerQtl: 2600 },
  { cropName: 'Tomato', marketName: 'Amravati', pricePerQtl: 2150, referenceDate: '2026-09-02' },
  // Potato
  { cropName: 'Potato', marketName: 'Lasalgaon', pricePerQtl: 1800 },
  { cropName: 'Potato', marketName: 'Pune', pricePerQtl: 1700 },
  { cropName: 'Potato', marketName: 'Nashik', pricePerQtl: 1650 },
  { cropName: 'Potato', marketName: 'Azadpur', pricePerQtl: 1600 },
  { cropName: 'Potato', marketName: 'Varanasi', pricePerQtl: 1900 },
  { cropName: 'Potato', marketName: 'Mathura', pricePerQtl: 1550, referenceDate: '2026-09-02' },
  // Rice
  { cropName: 'Rice', marketName: 'Lasalgaon', pricePerQtl: 3050 },
  { cropName: 'Rice', marketName: 'Pune', pricePerQtl: 3100 },
  { cropName: 'Rice', marketName: 'Nashik', pricePerQtl: 3150 },
  { cropName: 'Rice', marketName: 'Azadpur', pricePerQtl: 3350 },
  { cropName: 'Rice', marketName: 'Varanasi', pricePerQtl: 3200 },
  { cropName: 'Rice', marketName: 'Karnal', pricePerQtl: 3000, referenceDate: '2026-09-02' },
];

module.exports = {
  products,
  offers,
  marketPrices,
  MSAMB_DATE,
  DEMO_REQUIREMENT_IDS,
};